// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLsOUA9lKjwyaRX_ufOO-obHuLzEmwfCM',
    appId: '1:3307714742:web:61e382c3fbf4df1cba8e17',
    messagingSenderId: '3307714742',
    projectId: 'kurye-bacd4',
    authDomain: 'kurye-bacd4.firebaseapp.com',
    storageBucket: 'kurye-bacd4.firebasestorage.app',
    measurementId: 'G-DJXJZTQP86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkDd92Y_Qdh-kNnQAQc25R3pXzTIVr3JY',
    appId: '1:3307714742:android:dc63bf59dca47527ba8e17',
    messagingSenderId: '3307714742',
    projectId: 'kurye-bacd4',
    storageBucket: 'kurye-bacd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBANFzmlMVySUQy93YkZ0kT0HeKz5AtZIo',
    appId: '1:3307714742:ios:5e14cdfba2d16112ba8e17',
    messagingSenderId: '3307714742',
    projectId: 'kurye-bacd4',
    storageBucket: 'kurye-bacd4.firebasestorage.app',
    iosBundleId: 'com.kurye.kuryeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBANFzmlMVySUQy93YkZ0kT0HeKz5AtZIo',
    appId: '1:3307714742:ios:5e14cdfba2d16112ba8e17',
    messagingSenderId: '3307714742',
    projectId: 'kurye-bacd4',
    storageBucket: 'kurye-bacd4.firebasestorage.app',
    iosBundleId: 'com.kurye.kuryeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLsOUA9lKjwyaRX_ufOO-obHuLzEmwfCM',
    appId: '1:3307714742:web:958ea7c40e21f436ba8e17',
    messagingSenderId: '3307714742',
    projectId: 'kurye-bacd4',
    authDomain: 'kurye-bacd4.firebaseapp.com',
    storageBucket: 'kurye-bacd4.firebasestorage.app',
    measurementId: 'G-MSG9D111KH',
  );
}
